export interface Country {
  code: string;
  name: string;
  nameAr: string;
  flag: string;
}

export function countryCodeToFlag(code: string): string {
  const upper = code.toUpperCase();
  const codePoints = [...upper].map(
    (c) => 0x1f1e6 + c.charCodeAt(0) - 65
  );
  return String.fromCodePoint(...codePoints);
}

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", nameAr: "أفغانستان", flag: countryCodeToFlag("AF") },
  { code: "AL", name: "Albania", nameAr: "ألبانيا", flag: countryCodeToFlag("AL") },
  { code: "DZ", name: "Algeria", nameAr: "الجزائر", flag: countryCodeToFlag("DZ") },
  { code: "AS", name: "American Samoa", nameAr: "ساموا الأمريكية", flag: countryCodeToFlag("AS") },
  { code: "AD", name: "Andorra", nameAr: "أندورا", flag: countryCodeToFlag("AD") },
  { code: "AO", name: "Angola", nameAr: "أنغولا", flag: countryCodeToFlag("AO") },
  { code: "AI", name: "Anguilla", nameAr: "أنغيلا", flag: countryCodeToFlag("AI") },
  { code: "AG", name: "Antigua and Barbuda", nameAr: "أنتيغوا وبربودا", flag: countryCodeToFlag("AG") },
  { code: "AR", name: "Argentina", nameAr: "الأرجنتين", flag: countryCodeToFlag("AR") },
  { code: "AM", name: "Armenia", nameAr: "أرمينيا", flag: countryCodeToFlag("AM") },
  { code: "AW", name: "Aruba", nameAr: "أروبا", flag: countryCodeToFlag("AW") },
  { code: "AU", name: "Australia", nameAr: "أستراليا", flag: countryCodeToFlag("AU") },
  { code: "AT", name: "Austria", nameAr: "النمسا", flag: countryCodeToFlag("AT") },
  { code: "AZ", name: "Azerbaijan", nameAr: "أذربيجان", flag: countryCodeToFlag("AZ") },
  { code: "BS", name: "Bahamas", nameAr: "الباهاما", flag: countryCodeToFlag("BS") },
  { code: "BH", name: "Bahrain", nameAr: "البحرين", flag: countryCodeToFlag("BH") },
  { code: "BD", name: "Bangladesh", nameAr: "بنغلاديش", flag: countryCodeToFlag("BD") },
  { code: "BB", name: "Barbados", nameAr: "بربادوس", flag: countryCodeToFlag("BB") },
  { code: "BY", name: "Belarus", nameAr: "بيلاروسيا", flag: countryCodeToFlag("BY") },
  { code: "BE", name: "Belgium", nameAr: "بلجيكا", flag: countryCodeToFlag("BE") },
  { code: "BZ", name: "Belize", nameAr: "بليز", flag: countryCodeToFlag("BZ") },
  { code: "BJ", name: "Benin", nameAr: "بنين", flag: countryCodeToFlag("BJ") },
  { code: "BM", name: "Bermuda", nameAr: "برمودا", flag: countryCodeToFlag("BM") },
  { code: "BT", name: "Bhutan", nameAr: "بوتان", flag: countryCodeToFlag("BT") },
  { code: "BO", name: "Bolivia", nameAr: "بوليفيا", flag: countryCodeToFlag("BO") },
  { code: "BA", name: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك", flag: countryCodeToFlag("BA") },
  { code: "BW", name: "Botswana", nameAr: "بوتسوانا", flag: countryCodeToFlag("BW") },
  { code: "BR", name: "Brazil", nameAr: "البرازيل", flag: countryCodeToFlag("BR") },
  { code: "BN", name: "Brunei", nameAr: "بروناي", flag: countryCodeToFlag("BN") },
  { code: "BG", name: "Bulgaria", nameAr: "بلغاريا", flag: countryCodeToFlag("BG") },
  { code: "BF", name: "Burkina Faso", nameAr: "بوركينا فاسو", flag: countryCodeToFlag("BF") },
  { code: "BI", name: "Burundi", nameAr: "بوروندي", flag: countryCodeToFlag("BI") },
  { code: "CV", name: "Cabo Verde", nameAr: "الرأس الأخضر", flag: countryCodeToFlag("CV") },
  { code: "KH", name: "Cambodia", nameAr: "كمبوديا", flag: countryCodeToFlag("KH") },
  { code: "CM", name: "Cameroon", nameAr: "الكاميرون", flag: countryCodeToFlag("CM") },
  { code: "CA", name: "Canada", nameAr: "كندا", flag: countryCodeToFlag("CA") },
  { code: "KY", name: "Cayman Islands", nameAr: "جزر كايمان", flag: countryCodeToFlag("KY") },
  { code: "CF", name: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى", flag: countryCodeToFlag("CF") },
  { code: "TD", name: "Chad", nameAr: "تشاد", flag: countryCodeToFlag("TD") },
  { code: "CL", name: "Chile", nameAr: "تشيلي", flag: countryCodeToFlag("CL") },
  { code: "CN", name: "China", nameAr: "الصين", flag: countryCodeToFlag("CN") },
  { code: "CO", name: "Colombia", nameAr: "كولومبيا", flag: countryCodeToFlag("CO") },
  { code: "KM", name: "Comoros", nameAr: "جزر القمر", flag: countryCodeToFlag("KM") },
  { code: "CG", name: "Congo", nameAr: "الكونغو", flag: countryCodeToFlag("CG") },
  { code: "CD", name: "Congo (DRC)", nameAr: "الكونغو الديمقراطية", flag: countryCodeToFlag("CD") },
  { code: "CR", name: "Costa Rica", nameAr: "كوستاريكا", flag: countryCodeToFlag("CR") },
  { code: "CI", name: "Côte d'Ivoire", nameAr: "ساحل العاج", flag: countryCodeToFlag("CI") },
  { code: "HR", name: "Croatia", nameAr: "كرواتيا", flag: countryCodeToFlag("HR") },
  { code: "CU", name: "Cuba", nameAr: "كوبا", flag: countryCodeToFlag("CU") },
  { code: "CW", name: "Curaçao", nameAr: "كوراساو", flag: countryCodeToFlag("CW") },
  { code: "CY", name: "Cyprus", nameAr: "قبرص", flag: countryCodeToFlag("CY") },
  { code: "CZ", name: "Czech Republic", nameAr: "التشيك", flag: countryCodeToFlag("CZ") },
  { code: "DK", name: "Denmark", nameAr: "الدنمارك", flag: countryCodeToFlag("DK") },
  { code: "DJ", name: "Djibouti", nameAr: "جيبوتي", flag: countryCodeToFlag("DJ") },
  { code: "DM", name: "Dominica", nameAr: "دومينيكا", flag: countryCodeToFlag("DM") },
  { code: "DO", name: "Dominican Republic", nameAr: "جمهورية الدومينيكان", flag: countryCodeToFlag("DO") },
  { code: "EC", name: "Ecuador", nameAr: "الإكوادور", flag: countryCodeToFlag("EC") },
  { code: "EG", name: "Egypt", nameAr: "مصر", flag: countryCodeToFlag("EG") },
  { code: "SV", name: "El Salvador", nameAr: "السلفادور", flag: countryCodeToFlag("SV") },
  { code: "GQ", name: "Equatorial Guinea", nameAr: "غينيا الاستوائية", flag: countryCodeToFlag("GQ") },
  { code: "ER", name: "Eritrea", nameAr: "إريتريا", flag: countryCodeToFlag("ER") },
  { code: "EE", name: "Estonia", nameAr: "إستونيا", flag: countryCodeToFlag("EE") },
  { code: "SZ", name: "Eswatini", nameAr: "إسواتيني", flag: countryCodeToFlag("SZ") },
  { code: "ET", name: "Ethiopia", nameAr: "إثيوبيا", flag: countryCodeToFlag("ET") },
  { code: "FK", name: "Falkland Islands", nameAr: "جزر فوكلاند", flag: countryCodeToFlag("FK") },
  { code: "FO", name: "Faroe Islands", nameAr: "جزر فارو", flag: countryCodeToFlag("FO") },
  { code: "FJ", name: "Fiji", nameAr: "فيجي", flag: countryCodeToFlag("FJ") },
  { code: "FI", name: "Finland", nameAr: "فنلندا", flag: countryCodeToFlag("FI") },
  { code: "FR", name: "France", nameAr: "فرنسا", flag: countryCodeToFlag("FR") },
  { code: "GF", name: "French Guiana", nameAr: "غيانا الفرنسية", flag: countryCodeToFlag("GF") },
  { code: "PF", name: "French Polynesia", nameAr: "بولينيزيا الفرنسية", flag: countryCodeToFlag("PF") },
  { code: "GA", name: "Gabon", nameAr: "الغابون", flag: countryCodeToFlag("GA") },
  { code: "GM", name: "Gambia", nameAr: "غامبيا", flag: countryCodeToFlag("GM") },
  { code: "GE", name: "Georgia", nameAr: "جورجيا", flag: countryCodeToFlag("GE") },
  { code: "DE", name: "Germany", nameAr: "ألمانيا", flag: countryCodeToFlag("DE") },
  { code: "GH", name: "Ghana", nameAr: "غانا", flag: countryCodeToFlag("GH") },
  { code: "GI", name: "Gibraltar", nameAr: "جبل طارق", flag: countryCodeToFlag("GI") },
  { code: "GR", name: "Greece", nameAr: "اليونان", flag: countryCodeToFlag("GR") },
  { code: "GL", name: "Greenland", nameAr: "غرينلاند", flag: countryCodeToFlag("GL") },
  { code: "GD", name: "Grenada", nameAr: "غرينادا", flag: countryCodeToFlag("GD") },
  { code: "GP", name: "Guadeloupe", nameAr: "غوادلوب", flag: countryCodeToFlag("GP") },
  { code: "GU", name: "Guam", nameAr: "غوام", flag: countryCodeToFlag("GU") },
  { code: "GT", name: "Guatemala", nameAr: "غواتيمالا", flag: countryCodeToFlag("GT") },
  { code: "GN", name: "Guinea", nameAr: "غينيا", flag: countryCodeToFlag("GN") },
  { code: "GW", name: "Guinea-Bissau", nameAr: "غينيا بيساو", flag: countryCodeToFlag("GW") },
  { code: "GY", name: "Guyana", nameAr: "غيانا", flag: countryCodeToFlag("GY") },
  { code: "HT", name: "Haiti", nameAr: "هايتي", flag: countryCodeToFlag("HT") },
  { code: "HN", name: "Honduras", nameAr: "هندوراس", flag: countryCodeToFlag("HN") },
  { code: "HK", name: "Hong Kong", nameAr: "هونغ كونغ", flag: countryCodeToFlag("HK") },
  { code: "HU", name: "Hungary", nameAr: "المجر", flag: countryCodeToFlag("HU") },
  { code: "IS", name: "Iceland", nameAr: "آيسلندا", flag: countryCodeToFlag("IS") },
  { code: "IN", name: "India", nameAr: "الهند", flag: countryCodeToFlag("IN") },
  { code: "ID", name: "Indonesia", nameAr: "إندونيسيا", flag: countryCodeToFlag("ID") },
  { code: "IR", name: "Iran", nameAr: "إيران", flag: countryCodeToFlag("IR") },
  { code: "IQ", name: "Iraq", nameAr: "العراق", flag: countryCodeToFlag("IQ") },
  { code: "IE", name: "Ireland", nameAr: "أيرلندا", flag: countryCodeToFlag("IE") },
  { code: "IL", name: "Israel", nameAr: "إسرائيل", flag: countryCodeToFlag("IL") },
  { code: "IT", name: "Italy", nameAr: "إيطاليا", flag: countryCodeToFlag("IT") },
  { code: "JM", name: "Jamaica", nameAr: "جامايكا", flag: countryCodeToFlag("JM") },
  { code: "JP", name: "Japan", nameAr: "اليابان", flag: countryCodeToFlag("JP") },
  { code: "JO", name: "Jordan", nameAr: "الأردن", flag: countryCodeToFlag("JO") },
  { code: "KZ", name: "Kazakhstan", nameAr: "كازاخستان", flag: countryCodeToFlag("KZ") },
  { code: "KE", name: "Kenya", nameAr: "كينيا", flag: countryCodeToFlag("KE") },
  { code: "KI", name: "Kiribati", nameAr: "كيريباتي", flag: countryCodeToFlag("KI") },
  { code: "XK", name: "Kosovo", nameAr: "كوسوفو", flag: countryCodeToFlag("XK") },
  { code: "KW", name: "Kuwait", nameAr: "الكويت", flag: countryCodeToFlag("KW") },
  { code: "KG", name: "Kyrgyzstan", nameAr: "قيرغيزستان", flag: countryCodeToFlag("KG") },
  { code: "LA", name: "Laos", nameAr: "لاوس", flag: countryCodeToFlag("LA") },
  { code: "LV", name: "Latvia", nameAr: "لاتفيا", flag: countryCodeToFlag("LV") },
  { code: "LB", name: "Lebanon", nameAr: "لبنان", flag: countryCodeToFlag("LB") },
  { code: "LS", name: "Lesotho", nameAr: "ليسوتو", flag: countryCodeToFlag("LS") },
  { code: "LR", name: "Liberia", nameAr: "ليبيريا", flag: countryCodeToFlag("LR") },
  { code: "LY", name: "Libya", nameAr: "ليبيا", flag: countryCodeToFlag("LY") },
  { code: "LI", name: "Liechtenstein", nameAr: "ليختنشتاين", flag: countryCodeToFlag("LI") },
  { code: "LT", name: "Lithuania", nameAr: "ليتوانيا", flag: countryCodeToFlag("LT") },
  { code: "LU", name: "Luxembourg", nameAr: "لوكسمبورغ", flag: countryCodeToFlag("LU") },
  { code: "MO", name: "Macau", nameAr: "ماكاو", flag: countryCodeToFlag("MO") },
  { code: "MG", name: "Madagascar", nameAr: "مدغشقر", flag: countryCodeToFlag("MG") },
  { code: "MW", name: "Malawi", nameAr: "ملاوي", flag: countryCodeToFlag("MW") },
  { code: "MY", name: "Malaysia", nameAr: "ماليزيا", flag: countryCodeToFlag("MY") },
  { code: "MV", name: "Maldives", nameAr: "المالديف", flag: countryCodeToFlag("MV") },
  { code: "ML", name: "Mali", nameAr: "مالي", flag: countryCodeToFlag("ML") },
  { code: "MT", name: "Malta", nameAr: "مالطا", flag: countryCodeToFlag("MT") },
  { code: "MH", name: "Marshall Islands", nameAr: "جزر مارشال", flag: countryCodeToFlag("MH") },
  { code: "MQ", name: "Martinique", nameAr: "مارتينيك", flag: countryCodeToFlag("MQ") },
  { code: "MR", name: "Mauritania", nameAr: "موريتانيا", flag: countryCodeToFlag("MR") },
  { code: "MU", name: "Mauritius", nameAr: "موريشيوس", flag: countryCodeToFlag("MU") },
  { code: "MX", name: "Mexico", nameAr: "المكسيك", flag: countryCodeToFlag("MX") },
  { code: "FM", name: "Micronesia", nameAr: "ميكرونيزيا", flag: countryCodeToFlag("FM") },
  { code: "MD", name: "Moldova", nameAr: "مولدوفا", flag: countryCodeToFlag("MD") },
  { code: "MC", name: "Monaco", nameAr: "موناكو", flag: countryCodeToFlag("MC") },
  { code: "MN", name: "Mongolia", nameAr: "منغوليا", flag: countryCodeToFlag("MN") },
  { code: "ME", name: "Montenegro", nameAr: "الجبل الأسود", flag: countryCodeToFlag("ME") },
  { code: "MS", name: "Montserrat", nameAr: "مونتسرات", flag: countryCodeToFlag("MS") },
  { code: "MA", name: "Morocco", nameAr: "المغرب", flag: countryCodeToFlag("MA") },
  { code: "MZ", name: "Mozambique", nameAr: "موزمبيق", flag: countryCodeToFlag("MZ") },
  { code: "MM", name: "Myanmar", nameAr: "ميانمار", flag: countryCodeToFlag("MM") },
  { code: "NA", name: "Namibia", nameAr: "ناميبيا", flag: countryCodeToFlag("NA") },
  { code: "NR", name: "Nauru", nameAr: "ناورو", flag: countryCodeToFlag("NR") },
  { code: "NP", name: "Nepal", nameAr: "نيبال", flag: countryCodeToFlag("NP") },
  { code: "NL", name: "Netherlands", nameAr: "هولندا", flag: countryCodeToFlag("NL") },
  { code: "NC", name: "New Caledonia", nameAr: "كاليدونيا الجديدة", flag: countryCodeToFlag("NC") },
  { code: "NZ", name: "New Zealand", nameAr: "نيوزيلندا", flag: countryCodeToFlag("NZ") },
  { code: "NI", name: "Nicaragua", nameAr: "نيكاراغوا", flag: countryCodeToFlag("NI") },
  { code: "NE", name: "Niger", nameAr: "النيجر", flag: countryCodeToFlag("NE") },
  { code: "NG", name: "Nigeria", nameAr: "نيجيريا", flag: countryCodeToFlag("NG") },
  { code: "KP", name: "North Korea", nameAr: "كوريا الشمالية", flag: countryCodeToFlag("KP") },
  { code: "MK", name: "North Macedonia", nameAr: "مقدونيا الشمالية", flag: countryCodeToFlag("MK") },
  { code: "NO", name: "Norway", nameAr: "النرويج", flag: countryCodeToFlag("NO") },
  { code: "OM", name: "Oman", nameAr: "عُمان", flag: countryCodeToFlag("OM") },
  { code: "PK", name: "Pakistan", nameAr: "باكستان", flag: countryCodeToFlag("PK") },
  { code: "PW", name: "Palau", nameAr: "بالاو", flag: countryCodeToFlag("PW") },
  { code: "PS", name: "Palestine", nameAr: "فلسطين", flag: countryCodeToFlag("PS") },
  { code: "PA", name: "Panama", nameAr: "بنما", flag: countryCodeToFlag("PA") },
  { code: "PG", name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", flag: countryCodeToFlag("PG") },
  { code: "PY", name: "Paraguay", nameAr: "باراغواي", flag: countryCodeToFlag("PY") },
  { code: "PE", name: "Peru", nameAr: "بيرو", flag: countryCodeToFlag("PE") },
  { code: "PH", name: "Philippines", nameAr: "الفلبين", flag: countryCodeToFlag("PH") },
  { code: "PL", name: "Poland", nameAr: "بولندا", flag: countryCodeToFlag("PL") },
  { code: "PT", name: "Portugal", nameAr: "البرتغال", flag: countryCodeToFlag("PT") },
  { code: "PR", name: "Puerto Rico", nameAr: "بورتوريكو", flag: countryCodeToFlag("PR") },
  { code: "QA", name: "Qatar", nameAr: "قطر", flag: countryCodeToFlag("QA") },
  { code: "RE", name: "Réunion", nameAr: "ريونيون", flag: countryCodeToFlag("RE") },
  { code: "RO", name: "Romania", nameAr: "رومانيا", flag: countryCodeToFlag("RO") },
  { code: "RU", name: "Russia", nameAr: "روسيا", flag: countryCodeToFlag("RU") },
  { code: "RW", name: "Rwanda", nameAr: "رواندا", flag: countryCodeToFlag("RW") },
  { code: "KN", name: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس", flag: countryCodeToFlag("KN") },
  { code: "LC", name: "Saint Lucia", nameAr: "سانت لوسيا", flag: countryCodeToFlag("LC") },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameAr: "سانت فنسنت والغرينادين", flag: countryCodeToFlag("VC") },
  { code: "WS", name: "Samoa", nameAr: "ساموا", flag: countryCodeToFlag("WS") },
  { code: "SM", name: "San Marino", nameAr: "سان مارينو", flag: countryCodeToFlag("SM") },
  { code: "ST", name: "São Tomé and Príncipe", nameAr: "ساو تومي وبرينسيبي", flag: countryCodeToFlag("ST") },
  { code: "SA", name: "Saudi Arabia", nameAr: "المملكة العربية السعودية", flag: countryCodeToFlag("SA") },
  { code: "SN", name: "Senegal", nameAr: "السنغال", flag: countryCodeToFlag("SN") },
  { code: "RS", name: "Serbia", nameAr: "صربيا", flag: countryCodeToFlag("RS") },
  { code: "SC", name: "Seychelles", nameAr: "سيشل", flag: countryCodeToFlag("SC") },
  { code: "SL", name: "Sierra Leone", nameAr: "سيراليون", flag: countryCodeToFlag("SL") },
  { code: "SG", name: "Singapore", nameAr: "سنغافورة", flag: countryCodeToFlag("SG") },
  { code: "SX", name: "Sint Maarten", nameAr: "سينت مارتن", flag: countryCodeToFlag("SX") },
  { code: "SK", name: "Slovakia", nameAr: "سلوفاكيا", flag: countryCodeToFlag("SK") },
  { code: "SI", name: "Slovenia", nameAr: "سلوفينيا", flag: countryCodeToFlag("SI") },
  { code: "SB", name: "Solomon Islands", nameAr: "جزر سليمان", flag: countryCodeToFlag("SB") },
  { code: "SO", name: "Somalia", nameAr: "الصومال", flag: countryCodeToFlag("SO") },
  { code: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا", flag: countryCodeToFlag("ZA") },
  { code: "KR", name: "South Korea", nameAr: "كوريا الجنوبية", flag: countryCodeToFlag("KR") },
  { code: "SS", name: "South Sudan", nameAr: "جنوب السودان", flag: countryCodeToFlag("SS") },
  { code: "ES", name: "Spain", nameAr: "إسبانيا", flag: countryCodeToFlag("ES") },
  { code: "LK", name: "Sri Lanka", nameAr: "سريلانكا", flag: countryCodeToFlag("LK") },
  { code: "SD", name: "Sudan", nameAr: "السودان", flag: countryCodeToFlag("SD") },
  { code: "SR", name: "Suriname", nameAr: "سورينام", flag: countryCodeToFlag("SR") },
  { code: "SE", name: "Sweden", nameAr: "السويد", flag: countryCodeToFlag("SE") },
  { code: "CH", name: "Switzerland", nameAr: "سويسرا", flag: countryCodeToFlag("CH") },
  { code: "SY", name: "Syria", nameAr: "سوريا", flag: countryCodeToFlag("SY") },
  { code: "TW", name: "Taiwan", nameAr: "تايوان", flag: countryCodeToFlag("TW") },
  { code: "TJ", name: "Tajikistan", nameAr: "طاجيكستان", flag: countryCodeToFlag("TJ") },
  { code: "TZ", name: "Tanzania", nameAr: "تنزانيا", flag: countryCodeToFlag("TZ") },
  { code: "TH", name: "Thailand", nameAr: "تايلاند", flag: countryCodeToFlag("TH") },
  { code: "TL", name: "Timor-Leste", nameAr: "تيمور الشرقية", flag: countryCodeToFlag("TL") },
  { code: "TG", name: "Togo", nameAr: "توغو", flag: countryCodeToFlag("TG") },
  { code: "TO", name: "Tonga", nameAr: "تونغا", flag: countryCodeToFlag("TO") },
  { code: "TT", name: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو", flag: countryCodeToFlag("TT") },
  { code: "TN", name: "Tunisia", nameAr: "تونس", flag: countryCodeToFlag("TN") },
  { code: "TR", name: "Turkey", nameAr: "تركيا", flag: countryCodeToFlag("TR") },
  { code: "TM", name: "Turkmenistan", nameAr: "تركمانستان", flag: countryCodeToFlag("TM") },
  { code: "TC", name: "Turks and Caicos Islands", nameAr: "جزر تركس وكايكوس", flag: countryCodeToFlag("TC") },
  { code: "TV", name: "Tuvalu", nameAr: "توفالو", flag: countryCodeToFlag("TV") },
  { code: "UG", name: "Uganda", nameAr: "أوغندا", flag: countryCodeToFlag("UG") },
  { code: "UA", name: "Ukraine", nameAr: "أوكرانيا", flag: countryCodeToFlag("UA") },
  { code: "AE", name: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة", flag: countryCodeToFlag("AE") },
  { code: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة", flag: countryCodeToFlag("GB") },
  { code: "US", name: "United States", nameAr: "الولايات المتحدة", flag: countryCodeToFlag("US") },
  { code: "UY", name: "Uruguay", nameAr: "أوروغواي", flag: countryCodeToFlag("UY") },
  { code: "UZ", name: "Uzbekistan", nameAr: "أوزبكستان", flag: countryCodeToFlag("UZ") },
  { code: "VU", name: "Vanuatu", nameAr: "فانواتو", flag: countryCodeToFlag("VU") },
  { code: "VA", name: "Vatican City", nameAr: "الفاتيكان", flag: countryCodeToFlag("VA") },
  { code: "VE", name: "Venezuela", nameAr: "فنزويلا", flag: countryCodeToFlag("VE") },
  { code: "VN", name: "Vietnam", nameAr: "فيتنام", flag: countryCodeToFlag("VN") },
  { code: "VI", name: "Virgin Islands (US)", nameAr: "جزر العذراء الأمريكية", flag: countryCodeToFlag("VI") },
  { code: "VG", name: "Virgin Islands (British)", nameAr: "جزر العذراء البريطانية", flag: countryCodeToFlag("VG") },
  { code: "YE", name: "Yemen", nameAr: "اليمن", flag: countryCodeToFlag("YE") },
  { code: "ZM", name: "Zambia", nameAr: "زامبيا", flag: countryCodeToFlag("ZM") },
  { code: "ZW", name: "Zimbabwe", nameAr: "زيمبابوي", flag: countryCodeToFlag("ZW") },
];

export const countryMap = new Map(countries.map((c) => [c.code, c]));

export function getCountryByCode(code: string | null | undefined): Country | undefined {
  if (!code) return undefined;
  return countryMap.get(code.toUpperCase());
}
